### ISSUE TITLE
derandomKnock package issue

### ISSUE THREAD

**Issue by yuxinrui1** [zhimeir/derandomKnock#1]
Hi Zhimei,

I have a question on derandomKnock package

When I follow your instruction on GitHub to install the package, and use library(derandomKnock), every function inside works

particularly what I want is get_parameter

While when I download your package locally, and run each function and want to get the res result.

An error occurs, which is 

Error in get_params(type = type, v = v, k = k, alpha = alpha, M = M, eta = eta,  : 
  object 'M_eta_mat' not found

It seems that there is no place defining the M_eta_mat.

I think it is a matrix for  M and eta. While I do not find place define this object. 

Could you please tell me why this happen?

Particularly it confuses me when I directly include your package while it works.

Hope for your reply!

**Comment by zhimeir** [comment]
Thanks for raising this issue! The `M_eta_mat` is stored in the file called "sysdata.rda". You can run 
`load(sysdata.rda)` 
and then run the get_params function. I'll also update the code to automatically load the data.

**Comment by yuxinrui1** [comment]
Thanks Zhimei!
